name       : xdg-desktop-portal-gnome
version    : 44.2
release    : 2
source     :
    - https://download.gnome.org/sources/xdg-desktop-portal-gnome/44/xdg-desktop-portal-gnome-44.2.tar.xz : 50ed1aac290303ea0bc5c840a9c1165918546ab4a73a24c52dcaa27072b5ff21
license    : LGPL-2.1-or-later
component  : desktop.util
summary    : A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
description: |
    A backend implementation for xdg-desktop-portal for the GNOME desktop environment.
builddeps  :
    - pkgconfig(evince-document-3.0)
    - pkgconfig(gnome-desktop-4)
    - pkgconfig(libadwaita-1)
    - pkgconfig(xdg-desktop-portal)
    - gnome-keyring
setup      : |
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
